/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BiographyRouteImport } from './routes/biography'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works.index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ExhibitionsIndexRouteImport } from './routes/exhibitions.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'
import { Route as ShopTermsRouteImport } from './routes/shop.terms'
import { Route as ShopReturnsRouteImport } from './routes/shop.returns'
import { Route as ShopInfoRouteImport } from './routes/shop.info'
import { Route as ShopFaqRouteImport } from './routes/shop.faq'
import { Route as ExhibitionsSlugRouteImport } from './routes/exhibitions.$slug'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as ShopProductIdRouteImport } from './routes/shop.product.$id'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BiographyRoute = BiographyRouteImport.update({
  id: '/biography',
  path: '/biography',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ExhibitionsIndexRoute = ExhibitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExhibitionsRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorksRoute,
} as any)
const ShopTermsRoute = ShopTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShopRoute,
} as any)
const ShopReturnsRoute = ShopReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => ShopRoute,
} as any)
const ShopInfoRoute = ShopInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ShopRoute,
} as any)
const ShopFaqRoute = ShopFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ShopRoute,
} as any)
const ExhibitionsSlugRoute = ExhibitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExhibitionsRoute,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/works': typeof WorksRouteWithChildren
  '/community/$slug': typeof CommunitySlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/shop/faq': typeof ShopFaqRoute
  '/shop/info': typeof ShopInfoRoute
  '/shop/returns': typeof ShopReturnsRoute
  '/shop/terms': typeof ShopTermsRoute
  '/works/$slug': typeof WorksSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/works/': typeof WorksIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/shop/faq': typeof ShopFaqRoute
  '/shop/info': typeof ShopInfoRoute
  '/shop/returns': typeof ShopReturnsRoute
  '/shop/terms': typeof ShopTermsRoute
  '/works/$slug': typeof WorksSlugRoute
  '/community': typeof CommunityIndexRoute
  '/exhibitions': typeof ExhibitionsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/works': typeof WorksIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/works': typeof WorksRouteWithChildren
  '/community/$slug': typeof CommunitySlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/shop/faq': typeof ShopFaqRoute
  '/shop/info': typeof ShopInfoRoute
  '/shop/returns': typeof ShopReturnsRoute
  '/shop/terms': typeof ShopTermsRoute
  '/works/$slug': typeof WorksSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/works/': typeof WorksIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biography'
    | '/community'
    | '/contact'
    | '/exhibitions'
    | '/shop'
    | '/sitemap.xml'
    | '/works'
    | '/community/$slug'
    | '/exhibitions/$slug'
    | '/shop/faq'
    | '/shop/info'
    | '/shop/returns'
    | '/shop/terms'
    | '/works/$slug'
    | '/community/'
    | '/exhibitions/'
    | '/shop/'
    | '/works/'
    | '/shop/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biography'
    | '/contact'
    | '/sitemap.xml'
    | '/community/$slug'
    | '/exhibitions/$slug'
    | '/shop/faq'
    | '/shop/info'
    | '/shop/returns'
    | '/shop/terms'
    | '/works/$slug'
    | '/community'
    | '/exhibitions'
    | '/shop'
    | '/works'
    | '/shop/product/$id'
  id:
    | '__root__'
    | '/'
    | '/biography'
    | '/community'
    | '/contact'
    | '/exhibitions'
    | '/shop'
    | '/sitemap.xml'
    | '/works'
    | '/community/$slug'
    | '/exhibitions/$slug'
    | '/shop/faq'
    | '/shop/info'
    | '/shop/returns'
    | '/shop/terms'
    | '/works/$slug'
    | '/community/'
    | '/exhibitions/'
    | '/shop/'
    | '/works/'
    | '/shop/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiographyRoute: typeof BiographyRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  ExhibitionsRoute: typeof ExhibitionsRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorksRoute: typeof WorksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biography': {
      id: '/biography'
      path: '/biography'
      fullPath: '/biography'
      preLoaderRoute: typeof BiographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof WorksRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/exhibitions/': {
      id: '/exhibitions/'
      path: '/'
      fullPath: '/exhibitions/'
      preLoaderRoute: typeof ExhibitionsIndexRouteImport
      parentRoute: typeof ExhibitionsRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof WorksRoute
    }
    '/shop/terms': {
      id: '/shop/terms'
      path: '/terms'
      fullPath: '/shop/terms'
      preLoaderRoute: typeof ShopTermsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/returns': {
      id: '/shop/returns'
      path: '/returns'
      fullPath: '/shop/returns'
      preLoaderRoute: typeof ShopReturnsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/info': {
      id: '/shop/info'
      path: '/info'
      fullPath: '/shop/info'
      preLoaderRoute: typeof ShopInfoRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/faq': {
      id: '/shop/faq'
      path: '/faq'
      fullPath: '/shop/faq'
      preLoaderRoute: typeof ShopFaqRouteImport
      parentRoute: typeof ShopRoute
    }
    '/exhibitions/$slug': {
      id: '/exhibitions/$slug'
      path: '/$slug'
      fullPath: '/exhibitions/$slug'
      preLoaderRoute: typeof ExhibitionsSlugRouteImport
      parentRoute: typeof ExhibitionsRoute
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunitySlugRoute: typeof CommunitySlugRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunitySlugRoute: CommunitySlugRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface ExhibitionsRouteChildren {
  ExhibitionsSlugRoute: typeof ExhibitionsSlugRoute
  ExhibitionsIndexRoute: typeof ExhibitionsIndexRoute
}

const ExhibitionsRouteChildren: ExhibitionsRouteChildren = {
  ExhibitionsSlugRoute: ExhibitionsSlugRoute,
  ExhibitionsIndexRoute: ExhibitionsIndexRoute,
}

const ExhibitionsRouteWithChildren = ExhibitionsRoute._addFileChildren(
  ExhibitionsRouteChildren,
)

interface ShopRouteChildren {
  ShopFaqRoute: typeof ShopFaqRoute
  ShopInfoRoute: typeof ShopInfoRoute
  ShopReturnsRoute: typeof ShopReturnsRoute
  ShopTermsRoute: typeof ShopTermsRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopFaqRoute: ShopFaqRoute,
  ShopInfoRoute: ShopInfoRoute,
  ShopReturnsRoute: ShopReturnsRoute,
  ShopTermsRoute: ShopTermsRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface WorksRouteChildren {
  WorksSlugRoute: typeof WorksSlugRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

const WorksRouteChildren: WorksRouteChildren = {
  WorksSlugRoute: WorksSlugRoute,
  WorksIndexRoute: WorksIndexRoute,
}

const WorksRouteWithChildren = WorksRoute._addFileChildren(WorksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiographyRoute: BiographyRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  ExhibitionsRoute: ExhibitionsRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorksRoute: WorksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
